# Exceptional Handling

- **Error:** errors can be fixed easily (eg: `SynTax Error:` can be fixed anyways)

- **Exceptions:** We can't fix exceptions (eg: `2/0` = No Solution)

## Syntax for exception handling

```python
try:
    raise Exception
except obj.Except:
    # code to handle exception
```

### Multiple `Except` Block

```python
try:
    raise Exception:
except 1:
    #code handle exp1
except 2:
    #code handle exp2
except 3:
    #code handle exp3
```

### `Else` and `Finally` Block

```python
try:
    raise Exception
except obj.Except:
    # code to handle exception
else:
    # code if there is no exception
finally:
    # code runs at last of exception handling (always executed)
```


### Examples of Exception

In [2]:
a=10
b = 2

In [3]:
a/0

ZeroDivisionError: division by zero

In [4]:
c

NameError: name 'c' is not defined

In [6]:
a=[1,2,3,4]

In [7]:
a[5]

IndexError: list index out of range

In [8]:
a=(1,2,3);b=(4,5,6)
a[5];b[10]

IndexError: tuple index out of range

In [9]:
population = {"India":35345, "US":93495349}

In [10]:
population["UK"]

KeyError: 'UK'

### Examples of error

In [11]:
open("test.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'test.csv'

In [5]:
if a

SyntaxError: invalid syntax (3320917452.py, line 1)

### Exception Handling (Example)

In [47]:
a=10

In [48]:
b=0

In [49]:
try:
    c=a/b
    print("result: ",c)
except ZeroDivisionError as ze:
    print(f"Zero Div error: {ze}")
except TypeError as te:
    print(f"Type got mismatched: {te}")
except Exception as e:
    print("Mistake:", e, sep=" ")
except IndexError as ie:
    print(f"Index got out of space")
else:
    print("Code executed successfully..........")
finally:
    print("Finally block executed....")

Zero Div error: division by zero
Finally block executed....


In [50]:
try:
    a=[1,2,3,]
    for x in range(5):
        print(a[x])
except IndexError as ie:
    print(f"Index got out of space")

1
2
3
Index got out of space


### Explicit exception `raise` keyword

In [54]:
age=9

In [57]:
try:
    if age>=18:
        print("OK")
    else:
        raise Exception
except Exception as e:
    print("Not excepted to vote this age.")
    print(e.__class__)

Not excepted to vote this age.
<class 'Exception'>


but we have to raise error `Not excepted to vote this age.` as a real-customized-exception. For that we use,

### Custom Exception creation

In [82]:
class CustomException(Exception):
    def __init__(self, msg, errorcode):
        super().__init__(msg)
        self.message = msg
        self.errorcode = errorcode
    def __str__(self):
        return f"{self.message}: Error code {self.errorcode}"

In [83]:
try:
    if age>=18:
        print("OK")
    else:
        raise CustomException("Not expected to vote", 900)
except CustomException as e:
    print(e)

Not expected to vote: Error code 900


In [77]:
help(Exception)

Help on class Exception in module builtins:

class Exception(BaseException)
 |  Common base class for all non-exit exceptions.
 |  
 |  Method resolution order:
 |      Exception
 |      BaseException
 |      object
 |  
 |  Built-in subclasses:
 |      ArithmeticError
 |      AssertionError
 |      AttributeError
 |      BufferError
 |      ... and 15 other subclasses
 |  
 |  Methods defined here:
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  ----------------------------------------------------------------------
 |  Methods inherited from BaseException:
 |  
 |  __delattr__(self, name, /)
 |      Implement delattr(self, name).
 |  
 |  __getattribute__(self, name, /

# `modules` and `packages`

- `modules` are the python files with functions and classes
- `packages` are collection of python files which are stored in a folder.

In [84]:
import sys

In [85]:
sys.path

['/home/varunm15t38hedu',
 '/opt/anaconda3/lib/python39.zip',
 '/opt/anaconda3/lib/python3.9',
 '/opt/anaconda3/lib/python3.9/lib-dynload',
 '',
 '/opt/anaconda3/lib/python3.9/site-packages',
 '/opt/anaconda3/lib/python3.9/site-packages/IPython/extensions',
 '/home/varunm15t38hedu/.ipython']

In [86]:
import os

In [97]:
import hello

In [98]:
hello.add(12,12)

24

In [93]:
hello.multiply(12,12)

144

In [94]:
from hello import add

In [95]:
add(12,12)

24

# `datetime` library

In [131]:
from datetime import datetime
from datetime import timedelta
from datetime import date

In [108]:
datetime.now()

datetime.datetime(2025, 5, 21, 7, 50, 56, 478132)

In [117]:
datetime.now().isocalendar()

datetime.IsoCalendarDate(year=2025, week=21, weekday=3)

In [120]:
d=date(2025,1,20)

In [121]:
d

datetime.date(2025, 1, 20)

In [112]:
datetime.now() - timedelta(days=1)

datetime.datetime(2025, 5, 20, 7, 51, 56, 248316)

In [113]:
datetime.now() - timedelta(weeks=1)

datetime.datetime(2025, 5, 14, 7, 52, 9, 487988)

In [116]:
datetime.now() - timedelta(days=30)

datetime.datetime(2025, 4, 21, 7, 53, 41, 615926)

In [122]:
datetime.now() + timedelta(days=30)

datetime.datetime(2025, 6, 20, 7, 57, 18, 350330)

In [124]:
import datetime

In [126]:
datetime.MAXYEAR

9999

In [127]:
datetime.MINYEAR

1

In [128]:
datetime.time

datetime.time

In [132]:
current_date = datetime.now()

In [135]:
current_date.strftime("%C-%A-%B")

'20-Wednesday-May'

# `Numpy` Module

- ### **_Arrays_**
    - homogenous data type
    - memory allocaation (continuous)
    - arrays on immutable
- ### **_Uses_**
    - used for faster computation and linear algebra operations
    - able to do operations in array

In [2]:
import numpy as np

In [159]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [140]:
a[1:5]

array([2, 3, 4, 5])

In [144]:
a = np.average(a)

In [190]:
ze = np.zeros((555,555,555))

In [191]:
ze

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [151]:
ze.dtype

dtype('float64')

In [152]:
ze.itemsize

8

In [188]:
fl=np.array(["marigold","sunflower"], dtype='<U10')

In [189]:
fl

array(['marigold', 'sunflower'], dtype='<U10')

In [184]:
fl.itemsize

36

In [185]:
fl.nbytes

72

In [192]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [203]:
rng = np.random.default_rng(seed=1298)

In [222]:
u1 = rng.integers(low=0,h, size=(55,55))

ValueError: high <= 0

In [209]:
u2 = rng.integers(low=500, high=10000, size=(55,55))

In [210]:
u1*u2

array([[ 130398, 3075807, 3854823, ..., 3463336,  373412, 3755836],
       [1012910,  787580, 2112506, ..., 9626084,   12048,  115425],
       [7392425,  199400, 2259390, ..., 2183892,  110565,  177672],
       ...,
       [4022207, 1251780, 4813584, ..., 1516991,   43056,  168462],
       [6507592, 7708248, 5079536, ...,  761760, 2128930,  438128],
       [3664625, 8816400,  973660, ..., 8535615,  137084, 5063355]])

In [211]:
u1@u2

array([[180582153, 131496525, 145694739, ..., 160925677, 146464585,
        181605316],
       [150100431, 103545821, 146086476, ..., 131145807, 111893652,
        150392984],
       [163720409, 140262639, 156325532, ..., 163976984, 145624082,
        176438825],
       ...,
       [150320735, 123891903, 136402561, ..., 134802783, 120241331,
        144162780],
       [157537014, 123103067, 140897323, ..., 154214404, 121620164,
        164701003],
       [160996821, 139588787, 147298500, ..., 162968969, 134422719,
        169360256]])

In [213]:
np.dot(u1,u2)

array([[180582153, 131496525, 145694739, ..., 160925677, 146464585,
        181605316],
       [150100431, 103545821, 146086476, ..., 131145807, 111893652,
        150392984],
       [163720409, 140262639, 156325532, ..., 163976984, 145624082,
        176438825],
       ...,
       [150320735, 123891903, 136402561, ..., 134802783, 120241331,
        144162780],
       [157537014, 123103067, 140897323, ..., 154214404, 121620164,
        164701003],
       [160996821, 139588787, 147298500, ..., 162968969, 134422719,
        169360256]])

In [223]:
np.multiply(u1,u2)

array([[ 130398, 3075807, 3854823, ..., 3463336,  373412, 3755836],
       [1012910,  787580, 2112506, ..., 9626084,   12048,  115425],
       [7392425,  199400, 2259390, ..., 2183892,  110565,  177672],
       ...,
       [4022207, 1251780, 4813584, ..., 1516991,   43056,  168462],
       [6507592, 7708248, 5079536, ...,  761760, 2128930,  438128],
       [3664625, 8816400,  973660, ..., 8535615,  137084, 5063355]])

In [228]:
np.cross(np.array([1,2,3]),np.array([4,5,6]))

array([-3,  6, -3])

In [215]:
u1.ndim

2

In [216]:
u2.ndim

2

In [217]:
u1.size

3025

In [218]:
u2.size

3025

In [219]:
u1.shape

(55, 55)

In [220]:
u2.shape

(55, 55)

### Get numpy array from dataset

In [231]:
data = np.genfromtxt("assets/datarray.txt", delimiter=",")

In [232]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [233]:
data[0]

array([  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
         8.,   0.,   1.,   2.,   3.,   4.,   5.])

In [234]:
data[0][4]

196.0

In [235]:
data.shape

(3, 18)

In [236]:
data[0][4:9]

array([196.,  75.,   4.,   3.,  34.])

In [237]:
data[2][4]

999.0

In [239]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [242]:
np.arange(1,41)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [252]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [255]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [257]:
arr1=np.array([1,2,3])

In [278]:
a1=np.repeat(arr1,10,axis=0).reshape(10,3)

In [279]:
a1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [281]:
np.repeat(a1,2,axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 2, 2],
       [1, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 3],
       [2, 2, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [61]:
a1 = np.arange(1,1000001).reshape(1000,1000)
a2 = np.arange(1,1000001).reshape(1000,1000)
a2 = a2.transpose()

In [4]:
a1+a2

array([[      2,    1003,    2004, ...,  997999,  999000, 1000001],
       [   1003,    2004,    3005, ...,  999000, 1000001, 1001002],
       [   2004,    3005,    4006, ..., 1000001, 1001002, 1002003],
       ...,
       [ 997999,  999000, 1000001, ..., 1995996, 1996997, 1997998],
       [ 999000, 1000001, 1001002, ..., 1996997, 1997998, 1998999],
       [1000001, 1001002, 1002003, ..., 1997998, 1998999, 2000000]])

In [5]:
a2 - a1

array([[      0,     999,    1998, ...,  996003,  997002,  998001],
       [   -999,       0,     999, ...,  995004,  996003,  997002],
       [  -1998,    -999,       0, ...,  994005,  995004,  996003],
       ...,
       [-996003, -995004, -994005, ...,       0,     999,    1998],
       [-997002, -996003, -995004, ...,    -999,       0,     999],
       [-998001, -997002, -996003, ...,   -1998,    -999,       0]])

In [6]:
a1*a2

array([[            1,          2002,          6003, ...,     995006998,
            997002999,     999001000],
       [         2002,       1004004,       2008006, ...,    1992009996,
           1995005998,    1998004000],
       [         6003,       2008006,       4012009, ...,    2989014994,
           2993010997,    2997009000],
       ...,
       [    995006998,    1992009996,    2989014994, ...,  996000008004,
         996999005002,  997998004000],
       [    997002999,    1995005998,    2993010997, ...,  996999005002,
         997999002001,  998999001000],
       [    999001000,    1998004000,    2997009000, ...,  997998004000,
         998999001000, 1000000000000]])

In [7]:
a2/a1

array([[1.00000000e+00, 5.00500000e+02, 6.67000000e+02, ...,
        9.98998998e+02, 9.99000000e+02, 9.99001000e+02],
       [1.99800200e-03, 1.00000000e+00, 1.99601196e+00, ...,
        4.99000000e+02, 4.99250625e+02, 4.99501000e+02],
       [1.49925037e-03, 5.00999001e-01, 1.00000000e+00, ...,
        3.32556037e+02, 3.32778593e+02, 3.33001000e+02],
       ...,
       [1.00100201e-03, 2.00400802e-03, 3.00701202e-03, ...,
        1.00000000e+00, 1.00100100e+00, 1.00200200e+00],
       [1.00100100e-03, 2.00300200e-03, 3.00500099e-03, ...,
        9.98999998e-01, 1.00000000e+00, 1.00100000e+00],
       [1.00100000e-03, 2.00199799e-03, 3.00299399e-03, ...,
        9.98001996e-01, 9.99000999e-01, 1.00000000e+00]])

In [8]:
a1//a2

array([[  1,   0,   0, ...,   0,   0,   0],
       [500,   1,   0, ...,   0,   0,   0],
       [667,   1,   1, ...,   0,   0,   0],
       ...,
       [998, 499, 332, ...,   1,   0,   0],
       [999, 499, 332, ...,   1,   1,   0],
       [999, 499, 333, ...,   1,   1,   1]])

In [9]:
a2//a1

array([[  1, 500, 667, ..., 998, 999, 999],
       [  0,   1,   1, ..., 499, 499, 499],
       [  0,   0,   1, ..., 332, 332, 333],
       ...,
       [  0,   0,   0, ...,   1,   1,   1],
       [  0,   0,   0, ...,   0,   1,   1],
       [  0,   0,   0, ...,   0,   0,   1]])

In [10]:
a1^a2

array([[     0,   1003,   2002, ..., 996719, 997782, 998833],
       [  1003,      0,   1081, ..., 995652, 998845, 997770],
       [  2002,   1081,      0, ..., 998717, 995780, 996835],
       ...,
       [996719, 995652, 998717, ...,      0,   1081,  30798],
       [997782, 998845, 995780, ...,   1081,      0,  31847],
       [998833, 997770, 996835, ...,  30798,  31847,      0]])

In [11]:
a1@a2

array([[      333833500,       834333500,      1334833500, ...,
           499332333500,    499832833500,    500333333500],
       [      834333500,      2334833500,      3835333500, ...,
          1496832833500,   1498333333500,   1499833833500],
       [     1334833500,      3835333500,      6335833500, ...,
          2494333333500,   2496833833500,   2499334333500],
       ...,
       [   499332333500,   1496832833500,   2494333333500, ...,
        995007330833500, 996004831333500, 997002331833500],
       [   499832833500,   1498333333500,   2496833833500, ...,
        996004831333500, 997003331833500, 998001832333500],
       [   500333333500,   1499833833500,   2499334333500, ...,
        997002331833500, 998001832333500, 999001332833500]])

In [12]:
np.average(a1)

500000.5

In [13]:
np.average(a2)

500000.5

In [14]:
np.mean(a1)

500000.5

In [16]:
np.average(a2,axis=0)

array([5.005000e+02, 1.500500e+03, 2.500500e+03, 3.500500e+03,
       4.500500e+03, 5.500500e+03, 6.500500e+03, 7.500500e+03,
       8.500500e+03, 9.500500e+03, 1.050050e+04, 1.150050e+04,
       1.250050e+04, 1.350050e+04, 1.450050e+04, 1.550050e+04,
       1.650050e+04, 1.750050e+04, 1.850050e+04, 1.950050e+04,
       2.050050e+04, 2.150050e+04, 2.250050e+04, 2.350050e+04,
       2.450050e+04, 2.550050e+04, 2.650050e+04, 2.750050e+04,
       2.850050e+04, 2.950050e+04, 3.050050e+04, 3.150050e+04,
       3.250050e+04, 3.350050e+04, 3.450050e+04, 3.550050e+04,
       3.650050e+04, 3.750050e+04, 3.850050e+04, 3.950050e+04,
       4.050050e+04, 4.150050e+04, 4.250050e+04, 4.350050e+04,
       4.450050e+04, 4.550050e+04, 4.650050e+04, 4.750050e+04,
       4.850050e+04, 4.950050e+04, 5.050050e+04, 5.150050e+04,
       5.250050e+04, 5.350050e+04, 5.450050e+04, 5.550050e+04,
       5.650050e+04, 5.750050e+04, 5.850050e+04, 5.950050e+04,
       6.050050e+04, 6.150050e+04, 6.250050e+04, 6.3500

In [17]:
np.matmul(a1,a2)

array([[      333833500,       834333500,      1334833500, ...,
           499332333500,    499832833500,    500333333500],
       [      834333500,      2334833500,      3835333500, ...,
          1496832833500,   1498333333500,   1499833833500],
       [     1334833500,      3835333500,      6335833500, ...,
          2494333333500,   2496833833500,   2499334333500],
       ...,
       [   499332333500,   1496832833500,   2494333333500, ...,
        995007330833500, 996004831333500, 997002331833500],
       [   499832833500,   1498333333500,   2496833833500, ...,
        996004831333500, 997003331833500, 998001832333500],
       [   500333333500,   1499833833500,   2499334333500, ...,
        997002331833500, 998001832333500, 999001332833500]])

In [27]:
np.all([np.array([True, True, False, True, False]),np.array([False, True, False, False, False])], axis=1)

array([False, False])

In [28]:
np.all([1,1,1])

True

In [36]:
a=[2,4,6,8,10,12,14,16,18,20]

In [37]:
np.all(np.array(a)%2==0,axis=0)

True

In [38]:
np.equal(a1,2)

array([[False,  True, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [39]:
np.equal(a2,2)

array([[False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [41]:
np.greater(a1,100)

array([[False, False, False, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [42]:
np.greater(a2,100)

array([[False,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       [False,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [43]:
np.less(a1,100)

array([[ True,  True,  True, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [44]:
np.less(a2,100)

array([[ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [45]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001, ..., -0.85547315,
        -0.02646075,  0.82687954],
       [ 0.9199906 ,  0.16726654, -0.7392416 , ..., -0.05290298,
         0.81170904,  0.9300395 ],
       [ 0.19329594, -0.72116302, -0.97258803, ...,  0.7959701 ,
         0.93943711,  0.21918997],
       ...,
       [-0.76006947, -0.95749033, -0.274599  , ...,  0.91801438,
         0.16232242, -0.74260803],
       [-0.96478808, -0.29994642,  0.6406646 , ...,  0.1883754 ,
        -0.72462655, -0.97141019],
       [-0.32508379,  0.62012315,  0.99519172, ..., -0.70613761,
        -0.97735203, -0.3499935 ]])

In [46]:
np.cos(a1)

array([[ 0.54030231, -0.41614684, -0.9899925 , ...,  0.51784716,
         0.99964985,  0.56237908],
       [-0.39194043, -0.98591171, -0.67344031, ...,  0.99859966,
         0.58406202, -0.36745955],
       [-0.9811405 , -0.6927654 ,  0.23253501, ...,  0.60533594,
        -0.34272134, -0.9756822 ],
       ...,
       [-0.64984183,  0.28846537,  0.96155883, ..., -0.39654709,
        -0.98673777, -0.6697263 ],
       [ 0.26302845,  0.95395605,  0.76782086, ..., -0.9820971 ,
        -0.68914176,  0.23740733],
       [ 0.94568522,  0.78450448, -0.09794606, ..., -0.70807463,
         0.21161996,  0.93675213]])

In [47]:
np.tan(a1)

array([[  1.55740772,  -2.18503986,  -0.14254654, ...,  -1.65197999,
         -0.02647002,   1.47032416],
       [ -2.34727149,  -0.16965671,   1.09770916, ...,  -0.05297716,
          1.38976515,  -2.53099833],
       [ -0.19701148,   1.04099168,  -4.18254442, ...,   1.31492291,
         -2.74111064,  -0.22465304],
       ...,
       [  1.16962226,  -3.31925575,  -0.28557691, ...,  -2.31501984,
         -0.16450411,   1.10882316],
       [ -3.66799899,  -0.31442373,   0.83439332, ...,  -0.19180935,
          1.05149127,  -4.09174473],
       [ -0.34375475,   0.79046477, -10.16060995, ...,   0.99726439,
         -4.61843033,  -0.37362445]])

In [50]:
1/np.sin(a1)

array([[  1.18839511,   1.09975017,   7.0861674 , ...,  -1.16894376,
        -37.79181983,   1.209366  ],
       [  1.08696763,   5.97848194,  -1.35273772, ..., -18.90252858,
          1.23196854,   1.07522314],
       [  5.1734144 ,  -1.38664903,  -1.02818457, ...,   1.2563286 ,
          1.06446721,   4.56225246],
       ...,
       [ -1.31566921,  -1.04439697,  -3.64167391, ...,   1.08930755,
          6.16057857,  -1.34660542],
       [ -1.03649705,  -3.33392881,   1.56087913, ...,   5.30854867,
         -1.38002121,  -1.02943124],
       [ -3.07613004,   1.61258291,   1.00483151, ...,  -1.41615456,
         -1.02317278,  -2.8571959 ]])

In [51]:
a1

array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

In [53]:
np.logical_and(a1,a2)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [55]:
np.logical_or(a1,a2)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [56]:
np.logical_not(a1)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [58]:
np.logical_xor(a1,a2)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

### Fancy indexing

**Syntax**
```python
array[[row1,row2,row3,row4],[col1,col2,col3,col4]]
```

In [64]:
a1[[0,1,2,3,4,5,6],[0,1,2,3,4,5,6]]

array([   1, 1002, 2003, 3004, 4005, 5006, 6007])

In [65]:
a1

array([[      1,       2,       3, ...,     998,     999,    1000],
       [   1001,    1002,    1003, ...,    1998,    1999,    2000],
       [   2001,    2002,    2003, ...,    2998,    2999,    3000],
       ...,
       [ 997001,  997002,  997003, ...,  997998,  997999,  998000],
       [ 998001,  998002,  998003, ...,  998998,  998999,  999000],
       [ 999001,  999002,  999003, ...,  999998,  999999, 1000000]])

In [70]:
c1 = np.arange(0,20).reshape(4,5)

In [71]:
c1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
c1[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [76]:
c1[:3,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [87]:
c1[[[1,1,1],[2,2,2],[3,3,3]],[[2,3,4],[2,3,4],[2,3,4]]]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [89]:
np.hsplit(a1,4)

[array([[     1,      2,      3, ...,    248,    249,    250],
        [  1001,   1002,   1003, ...,   1248,   1249,   1250],
        [  2001,   2002,   2003, ...,   2248,   2249,   2250],
        ...,
        [997001, 997002, 997003, ..., 997248, 997249, 997250],
        [998001, 998002, 998003, ..., 998248, 998249, 998250],
        [999001, 999002, 999003, ..., 999248, 999249, 999250]]),
 array([[   251,    252,    253, ...,    498,    499,    500],
        [  1251,   1252,   1253, ...,   1498,   1499,   1500],
        [  2251,   2252,   2253, ...,   2498,   2499,   2500],
        ...,
        [997251, 997252, 997253, ..., 997498, 997499, 997500],
        [998251, 998252, 998253, ..., 998498, 998499, 998500],
        [999251, 999252, 999253, ..., 999498, 999499, 999500]]),
 array([[   501,    502,    503, ...,    748,    749,    750],
        [  1501,   1502,   1503, ...,   1748,   1749,   1750],
        [  2501,   2502,   2503, ...,   2748,   2749,   2750],
        ...,
        [997

In [105]:
np.vsplit(a1,10)[0].shape

(100, 1000)

In [106]:
np.hsplit(a1,10)[0].shape

(1000, 100)

In [118]:
np.savetxt('assets/arr.txt',a1,fmt='%.1d')

In [119]:
a31 = np.genfromtxt('assets/arr.txt')

In [120]:
a31

array([[1.00000e+00, 2.00000e+00, 3.00000e+00, ..., 9.98000e+02,
        9.99000e+02, 1.00000e+03],
       [1.00100e+03, 1.00200e+03, 1.00300e+03, ..., 1.99800e+03,
        1.99900e+03, 2.00000e+03],
       [2.00100e+03, 2.00200e+03, 2.00300e+03, ..., 2.99800e+03,
        2.99900e+03, 3.00000e+03],
       ...,
       [9.97001e+05, 9.97002e+05, 9.97003e+05, ..., 9.97998e+05,
        9.97999e+05, 9.98000e+05],
       [9.98001e+05, 9.98002e+05, 9.98003e+05, ..., 9.98998e+05,
        9.98999e+05, 9.99000e+05],
       [9.99001e+05, 9.99002e+05, 9.99003e+05, ..., 9.99998e+05,
        9.99999e+05, 1.00000e+06]])

In [2]:
import numpy as np

In [3]:
datas = np.genfromtxt('assets/data_subplot.csv',delimiter=',',skip_header=True)

In [4]:
datas

array([[1.80000e+01, 1.77840e+04, 2.00460e+04, 1.64460e+04],
       [1.90000e+01, 1.65000e+04, 1.71000e+04, 1.67910e+04],
       [2.00000e+01, 1.80120e+04, 2.00000e+04, 1.89420e+04],
       [2.10000e+01, 2.06280e+04, 2.47440e+04, 2.17800e+04],
       [2.20000e+01, 2.52060e+04, 3.05000e+04, 2.57040e+04],
       [2.30000e+01, 3.02520e+04, 3.77320e+04, 2.90000e+04],
       [2.40000e+01, 3.43680e+04, 4.12470e+04, 3.43720e+04],
       [2.50000e+01, 3.84960e+04, 4.53720e+04, 3.78100e+04],
       [2.60000e+01, 4.20000e+04, 4.88760e+04, 4.35150e+04],
       [2.70000e+01, 4.67520e+04, 5.38500e+04, 4.68230e+04],
       [2.80000e+01, 4.93200e+04, 5.72870e+04, 4.92930e+04],
       [2.90000e+01, 5.32000e+04, 6.30160e+04, 5.34370e+04],
       [3.00000e+01, 5.60000e+04, 6.59980e+04, 5.63730e+04],
       [3.10000e+01, 6.23160e+04, 7.00030e+04, 6.23750e+04],
       [3.20000e+01, 6.49280e+04, 7.00000e+04, 6.66740e+04],
       [3.30000e+01, 6.73170e+04, 7.14960e+04, 6.87450e+04],
       [3.40000e+01, 6.8

In [131]:
np.average(datas,axis=0)[2]

75754.21052631579

In [159]:
mins=np.min(datas,axis=0)
print(mins[2],mins[3],sep="\n")

17100.0
16446.0


In [135]:
maxs=np.max(datas,axis=0)
print(maxs[2],maxs[3],sep="\n")

122870.0
108000.0


In [194]:
ages=datas[:,:1]

In [199]:
boolean=np.greater(ages,25).flatten()

In [201]:
datas[boolean]

array([[2.60000e+01, 4.20000e+04, 4.88760e+04, 4.35150e+04],
       [2.70000e+01, 4.67520e+04, 5.38500e+04, 4.68230e+04],
       [2.80000e+01, 4.93200e+04, 5.72870e+04, 4.92930e+04],
       [2.90000e+01, 5.32000e+04, 6.30160e+04, 5.34370e+04],
       [3.00000e+01, 5.60000e+04, 6.59980e+04, 5.63730e+04],
       [3.10000e+01, 6.23160e+04, 7.00030e+04, 6.23750e+04],
       [3.20000e+01, 6.49280e+04, 7.00000e+04, 6.66740e+04],
       [3.30000e+01, 6.73170e+04, 7.14960e+04, 6.87450e+04],
       [3.40000e+01, 6.87480e+04, 7.53700e+04, 6.87460e+04],
       [3.50000e+01, 7.37520e+04, 8.36400e+04, 7.45830e+04],
       [3.60000e+01, 7.72320e+04, 8.46660e+04, 7.90000e+04],
       [3.70000e+01, 7.80000e+04, 8.43920e+04, 7.85080e+04],
       [3.80000e+01, 7.85080e+04, 7.82540e+04, 7.99960e+04],
       [3.90000e+01, 7.95360e+04, 8.50000e+04, 8.04030e+04],
       [4.00000e+01, 8.24880e+04, 8.70380e+04, 8.38200e+04],
       [4.10000e+01, 8.89350e+04, 9.19910e+04, 8.88330e+04],
       [4.20000e+01, 9.0

In [191]:
datas[8:,:]

array([[2.60000e+01, 4.20000e+04, 4.88760e+04, 4.35150e+04],
       [2.70000e+01, 4.67520e+04, 5.38500e+04, 4.68230e+04],
       [2.80000e+01, 4.93200e+04, 5.72870e+04, 4.92930e+04],
       [2.90000e+01, 5.32000e+04, 6.30160e+04, 5.34370e+04],
       [3.00000e+01, 5.60000e+04, 6.59980e+04, 5.63730e+04],
       [3.10000e+01, 6.23160e+04, 7.00030e+04, 6.23750e+04],
       [3.20000e+01, 6.49280e+04, 7.00000e+04, 6.66740e+04],
       [3.30000e+01, 6.73170e+04, 7.14960e+04, 6.87450e+04],
       [3.40000e+01, 6.87480e+04, 7.53700e+04, 6.87460e+04],
       [3.50000e+01, 7.37520e+04, 8.36400e+04, 7.45830e+04],
       [3.60000e+01, 7.72320e+04, 8.46660e+04, 7.90000e+04],
       [3.70000e+01, 7.80000e+04, 8.43920e+04, 7.85080e+04],
       [3.80000e+01, 7.85080e+04, 7.82540e+04, 7.99960e+04],
       [3.90000e+01, 7.95360e+04, 8.50000e+04, 8.04030e+04],
       [4.00000e+01, 8.24880e+04, 8.70380e+04, 8.38200e+04],
       [4.10000e+01, 8.89350e+04, 9.19910e+04, 8.88330e+04],
       [4.20000e+01, 9.0

In [177]:
np.average(datas[:,1:2])

69257.07894736843

In [188]:
filters = datas[(datas[:,0]>=25)&(datas[:,0]<=30),1]

In [187]:
filters

array([[2.5000e+01, 3.8496e+04, 4.5372e+04, 3.7810e+04],
       [2.6000e+01, 4.2000e+04, 4.8876e+04, 4.3515e+04],
       [2.7000e+01, 4.6752e+04, 5.3850e+04, 4.6823e+04],
       [2.8000e+01, 4.9320e+04, 5.7287e+04, 4.9293e+04],
       [2.9000e+01, 5.3200e+04, 6.3016e+04, 5.3437e+04],
       [3.0000e+01, 5.6000e+04, 6.5998e+04, 5.6373e+04]])

In [186]:
np.max(filters)

65998.0

In [203]:
print(maxs[3] if maxs[3]>maxs[2] else maxs[2])

122870.0


In [205]:
for x in np.nditer(datas):
    print(x,sep=" ")

18.0
17784.0
20046.0
16446.0
19.0
16500.0
17100.0
16791.0
20.0
18012.0
20000.0
18942.0
21.0
20628.0
24744.0
21780.0
22.0
25206.0
30500.0
25704.0
23.0
30252.0
37732.0
29000.0
24.0
34368.0
41247.0
34372.0
25.0
38496.0
45372.0
37810.0
26.0
42000.0
48876.0
43515.0
27.0
46752.0
53850.0
46823.0
28.0
49320.0
57287.0
49293.0
29.0
53200.0
63016.0
53437.0
30.0
56000.0
65998.0
56373.0
31.0
62316.0
70003.0
62375.0
32.0
64928.0
70000.0
66674.0
33.0
67317.0
71496.0
68745.0
34.0
68748.0
75370.0
68746.0
35.0
73752.0
83640.0
74583.0
36.0
77232.0
84666.0
79000.0
37.0
78000.0
84392.0
78508.0
38.0
78508.0
78254.0
79996.0
39.0
79536.0
85000.0
80403.0
40.0
82488.0
87038.0
83820.0
41.0
88935.0
91991.0
88833.0
42.0
90000.0
100000.0
91660.0
43.0
90056.0
94796.0
87892.0
44.0
95000.0
97962.0
96243.0
45.0
90000.0
93302.0
90000.0
46.0
91633.0
99240.0
99313.0
47.0
91660.0
102736.0
91660.0
48.0
98150.0
112285.0
102264.0
49.0
98964.0
100771.0
100000.0
50.0
100000.0
104708.0
100000.0
51.0
98988.0
108423.0
91660.0
52.0

In [210]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [211]:
np.concatenate((a,b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [212]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [214]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [216]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [218]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [219]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [220]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [221]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

- single arr = age -> 18-25; 30-35
- single arr = age, python, JS

In [7]:
age1825 = np.logical_and(datas[:,:1]>=18,datas[:,:1]<=25)
age3035 = np.logical_and(datas[:,:1]>=30,datas[:,:1]<=35)

In [8]:
resbool = np.logical_or(age1825,age3035)

In [10]:
resbool = resbool.flatten()

In [20]:
result = np.hsplit(datas[resbool],4)

In [39]:
result1 = np.concatenate((result[0],result[2],result[3]),axis=1)

In [47]:
result1.astype(int)

array([[   18, 20046, 16446],
       [   19, 17100, 16791],
       [   20, 20000, 18942],
       [   21, 24744, 21780],
       [   22, 30500, 25704],
       [   23, 37732, 29000],
       [   24, 41247, 34372],
       [   25, 45372, 37810],
       [   30, 65998, 56373],
       [   31, 70003, 62375],
       [   32, 70000, 66674],
       [   33, 71496, 68745],
       [   34, 75370, 68746],
       [   35, 83640, 74583]])

In [51]:
np.savetxt("result.txt",result1.astype(int))

### Changing shape results to address remains same in the same array

In [23]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [41]:
id(a.reshape(5,2))

140264108109872

In [42]:
id(a)

140263914764400

In [43]:
np.shape = (2,5)

In [44]:
a.shape = (2,5)

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
id(a)

140263914764400